# Generated by Django 4.0 on 2021-12-24 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("surname", models.CharField(max_length=70, verbose_name="Фамилия")),
                (
                    "grade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(11),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "gpa",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Средний балл",
                    ),
                ),
            ],
        ),
    ]
